# Generated by Django 5.2.6 on 2025-10-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='doc_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='patient',
        ),
    ]
