# Generated by Django 5.2.8 on 2025-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
